services:
  - type: web
    name: pdf-compressor
    runtime: python
    buildCommand: |
      apt-get update
      apt-get install -y ghostscript libreoffice
      apt-get install -y poppler-utils
      pip install -r requirements.txt

    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 180 --workers 1
