services:
  - type: web
    name: pdf-compressor
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update
      apt-get install -y ghostscript
    startCommand: gunicorn app:app --timeout 120